# Generated by Django 5.2.4 on 2026-01-29 07:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogPekerjaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.localdate, verbose_name='Tanggal')),
                ('keterangan', models.TextField(verbose_name='Keterangan Catatan / Kejadian')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('pj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Penanggung Jawab (PJ)')),
            ],
            options={
                'verbose_name': 'Log Pekerjaan',
                'verbose_name_plural': 'Daftar Log Pekerjaan',
                'ordering': ['-tanggal', '-dibuat_pada'],
            },
        ),
    ]
