# Generated by Django 5.2.4 on 2025-07-17 03:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PenerimaanLinen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Penerimaan')),
                ('jam', models.TimeField(default=django.utils.timezone.now, verbose_name='Jam Penerimaan')),
                ('ruangan', models.CharField(choices=[('Kamar Bedah', 'Kamar Bedah'), ('Rawat Inap', 'Rawat Inap'), ('Rawat Jalan', 'Rawat Jalan'), ('IGD', 'IGD'), ('Penunjang Medis', 'Penunjang Medis'), ('Fasilitas Umum', 'Fasilitas Umum'), ('Lainnya', 'Lainnya')], max_length=100, verbose_name='Ruangan/Asal Linen')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('petugas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Petugas Penerima')),
            ],
            options={
                'verbose_name': 'Penerimaan Linen',
                'verbose_name_plural': 'Daftar Penerimaan Linen',
                'ordering': ['-tanggal', '-jam'],
            },
        ),
        migrations.CreateModel(
            name='ItemLinen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_item', models.CharField(choices=[('Baju Perawat', 'Baju Perawat'), ('Baju Dokter', 'Baju Dokter'), ('Baju Pasien', 'Baju Pasien'), ('Baju Cleaner', 'Baju Cleaner'), ('Doek Besar', 'Doek Besar'), ('Doek Kecil', 'Doek Kecil'), ('Handuk Kecil', 'Handuk Kecil'), ('Laken', 'Laken'), ('Sarung Bantal', 'Sarung Bantal'), ('Selimut', 'Selimut'), ('Handuk', 'Handuk'), ('Keset', 'Keset'), ('Gown Scrub', 'Gown Scrub'), ('Mukena', 'Mukena'), ('Sejadah', 'Sejadah'), ('Bedset', 'Bedset'), ('Gorden', 'Gorden')], max_length=100, verbose_name='Nama Item')),
                ('jumlah', models.PositiveIntegerField(default=1, verbose_name='Jumlah')),
                ('kondisi', models.CharField(choices=[('Baik', 'Baik'), ('Noda', 'Noda'), ('Rusak', 'Rusak')], default='Baik', max_length=10, verbose_name='Kondisi')),
                ('keterangan', models.CharField(blank=True, max_length=255, verbose_name='Keterangan')),
                ('penerimaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklist.penerimaanlinen')),
            ],
            options={
                'verbose_name': 'Item Linen',
                'verbose_name_plural': 'Daftar Item Linen',
            },
        ),
    ]
