# Generated by Django 5.2.4 on 2025-07-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penerimaanlinen',
            name='berat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Berat Linen (Kg)'),
        ),
        migrations.AlterField(
            model_name='itemlinen',
            name='nama_item',
            field=models.CharField(choices=[('Baju Perawat', 'Baju Perawat'), ('Baju Dokter', 'Baju Dokter'), ('Baju Pasien', 'Baju Pasien'), ('Baju Cleaner', 'Baju Cleaner'), ('Doek Besar', 'Doek Besar'), ('Doek Kecil', 'Doek Kecil'), ('Handuk Kecil', 'Handuk Kecil'), ('Laken', 'Laken'), ('Sarung Bantal', 'Sarung Bantal'), ('Selimut', 'Selimut'), ('Handuk', 'Handuk'), ('Keset', 'Keset'), ('Gown Scrub', 'Gown Scrub'), ('Mukena', 'Mukena'), ('Sejadah', 'Sejadah'), ('Bedset', 'Bedset'), ('Gorden', 'Gorden'), ('Linen Lainnya', 'Linen Lainnya')], max_length=100, verbose_name='Nama Item'),
        ),
    ]
