# Generated by Django 5.2.4 on 2025-07-18 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_penerimaanlinen_berat_alter_itemlinen_nama_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penerimaanlinen',
            name='berat',
        ),
        migrations.AlterField(
            model_name='itemlinen',
            name='nama_item',
            field=models.CharField(choices=[('Baju Perawat', 'Baju Perawat'), ('Baju Dokter', 'Baju Dokter'), ('Gorden', 'Gorden')], max_length=100, verbose_name='Nama Item'),
        ),
        migrations.CreateModel(
            name='BeratLinenHarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('ruangan', models.CharField(choices=[('Kamar Bedah', 'Kamar Bedah'), ('Rawat Inap', 'Rawat Inap'), ('Rawat Jalan', 'Rawat Jalan'), ('IGD', 'IGD'), ('Penunjang Medis', 'Penunjang Medis'), ('Fasilitas Umum', 'Fasilitas Umum'), ('Lainnya', 'Lainnya')], max_length=100, verbose_name='Ruangan')),
                ('total_berat', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Total Berat (Kg)')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('petugas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Berat Linen Harian',
                'verbose_name_plural': 'Data Berat Linen Harian',
                'ordering': ['-tanggal', 'ruangan'],
            },
        ),
    ]
