# Generated by Django 5.2.4 on 2025-07-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_remove_penerimaanlinen_berat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beratlinenharian',
            options={'ordering': ['-tanggal', 'ruangan', 'shift'], 'verbose_name': 'Berat Linen Harian', 'verbose_name_plural': 'Data Berat Linen Harian'},
        ),
        migrations.AddField(
            model_name='beratlinenharian',
            name='shift',
            field=models.CharField(choices=[('Shift 1', 'Shift 1'), ('Shift 2', 'Shift 2'), ('Shift 3', 'Shift 3')], default='Shift 1', max_length=10, verbose_name='Shift'),
        ),
        migrations.AlterField(
            model_name='itemlinen',
            name='nama_item',
            field=models.CharField(choices=[('Baju Perawat', 'Baju Perawat'), ('Baju Dokter', 'Baju Dokter'), ('Baju Pasien', 'Baju Pasien'), ('Baju Cleaner', 'Baju Cleaner'), ('Doek Besar', 'Doek Besar'), ('Doek Kecil', 'Doek Kecil'), ('Handuk Kecil', 'Handuk Kecil'), ('Laken', 'Laken'), ('Sarung Bantal', 'Sarung Bantal'), ('Selimut', 'Selimut'), ('Handuk', 'Handuk'), ('Keset', 'Keset'), ('Gown Scrub', 'Gown Scrub'), ('Mukena', 'Mukena'), ('Sejadah', 'Sejadah'), ('Bedset', 'Bedset'), ('Gorden', 'Gorden')], max_length=100, verbose_name='Nama Item'),
        ),
    ]
