# Generated by Django 5.2.4 on 2025-07-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_alter_beratlinenharian_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beratlinenharian',
            name='ruangan',
            field=models.CharField(choices=[('Kamar Bedah', 'Kamar Bedah'), ('Rawat Inap', 'Rawat Inap'), ('Rawat Jalan', 'Rawat Jalan'), ('IGD', 'IGD'), ('Penunjang Medis', 'Penunjang Medis'), ('Fasilitas Umum', 'Fasilitas Umum'), ('Ruang Istirahat Dokter', 'Ruang Istirahat Dokter'), ('Lainnya', 'Lainnya')], max_length=100, verbose_name='Ruangan'),
        ),
        migrations.AlterField(
            model_name='penerimaanlinen',
            name='ruangan',
            field=models.CharField(choices=[('Kamar Bedah', 'Kamar Bedah'), ('Rawat Inap', 'Rawat Inap'), ('Rawat Jalan', 'Rawat Jalan'), ('IGD', 'IGD'), ('Penunjang Medis', 'Penunjang Medis'), ('Fasilitas Umum', 'Fasilitas Umum'), ('Ruang Istirahat Dokter', 'Ruang Istirahat Dokter'), ('Lainnya', 'Lainnya')], max_length=100, verbose_name='Ruangan/Asal Linen'),
        ),
    ]
