# Generated by Django 5.2.4 on 2025-11-03 03:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0006_alter_beratlinenharian_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penerimaanlinen',
            name='jam',
            field=models.TimeField(default=django.utils.timezone.localdate, verbose_name='Jam Penerimaan'),
        ),
        migrations.AlterField(
            model_name='penerimaanlinen',
            name='tanggal',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Tanggal Penerimaan'),
        ),
    ]
