# Generated by Django 5.2.4 on 2025-07-18 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StokLinen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_linen', models.CharField(choices=[('Baju Perawat', 'Baju Perawat'), ('Baju Dokter', 'Baju Dokter'), ('Baju Pasien', 'Baju Pasien'), ('Baju Cleaner', 'Baju Cleaner'), ('Doek Besar', 'Doek Besar'), ('Doek Kecil', 'Doek Kecil'), ('Handuk Kecil', 'Handuk Kecil'), ('Laken', 'Laken'), ('Sarung Bantal', 'Sarung Bantal'), ('Selimut', 'Selimut'), ('Handuk', 'Handuk'), ('Keset', 'Keset'), ('Gown Scrub', 'Gown Scrub'), ('Mukena', 'Mukena'), ('Sejadah', 'Sejadah'), ('Bedset', 'Bedset'), ('Gorden', 'Gorden'), ('Linen Lainnya', 'Linen Lainnya')], max_length=100, verbose_name='Nama Linen')),
                ('ruangan', models.CharField(choices=[('Kamar Bedah', 'Kamar Bedah'), ('Rawat Inap', 'Rawat Inap'), ('Rawat Jalan', 'Rawat Jalan'), ('IGD', 'IGD'), ('Penunjang Medis', 'Penunjang Medis'), ('Fasilitas Umum', 'Fasilitas Umum'), ('Lainnya', 'Lainnya')], max_length=100, verbose_name='Ruangan')),
                ('stok_akhir', models.PositiveIntegerField(default=0, verbose_name='Stok Akhir')),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('update_terakhir', models.DateTimeField(auto_now=True, verbose_name='Update Terakhir')),
            ],
            options={
                'verbose_name': 'Stok Linen',
                'verbose_name_plural': 'Daftar Stok Linen',
                'ordering': ['ruangan', 'nama_linen'],
                'unique_together': {('nama_linen', 'ruangan')},
            },
        ),
        migrations.CreateModel(
            name='TransaksiLinen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_transaksi', models.CharField(choices=[('MASUK', 'Linen Masuk'), ('KELUAR', 'Linen Keluar')], max_length=10, verbose_name='Jenis Transaksi')),
                ('jumlah', models.PositiveIntegerField()),
                ('tanggal', models.DateField(verbose_name='Tanggal Transaksi')),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('petugas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('stok_linen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaksi', to='stok_linen.stoklinen', verbose_name='Item Linen')),
            ],
            options={
                'verbose_name': 'Transaksi Linen',
                'verbose_name_plural': 'Riwayat Transaksi Linen',
                'ordering': ['-tanggal'],
            },
        ),
    ]
