# Generated by Django 5.2.4 on 2025-08-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok_linen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoklinen',
            name='nama_linen',
            field=models.CharField(choices=[('Baju Perawat', 'Baju Perawat'), ('Baju Dokter', 'Baju Dokter'), ('Baju Pasien', 'Baju Pasien'), ('Baju Cleaner', 'Baju Cleaner'), ('Doek Besar', 'Doek Besar'), ('Doek Kecil', 'Doek Kecil'), ('Handuk Kecil', 'Handuk Kecil'), ('Laken', 'Laken'), ('Sarung Bantal', 'Sarung Bantal'), ('Selimut', 'Selimut'), ('Handuk', 'Handuk'), ('Keset', 'Keset'), ('Gown Scrub', 'Gown Scrub'), ('Mukena', 'Mukena'), ('Sejadah', 'Sejadah'), ('Bedset', 'Bedset'), ('Gorden', 'Gorden')], max_length=100, verbose_name='Nama Linen'),
        ),
        migrations.AlterField(
            model_name='stoklinen',
            name='ruangan',
            field=models.CharField(choices=[('Kamar Bedah', 'Kamar Bedah'), ('Rawat Inap', 'Rawat Inap'), ('Rawat Jalan', 'Rawat Jalan'), ('IGD', 'IGD'), ('Penunjang Medis', 'Penunjang Medis'), ('Fasilitas Umum', 'Fasilitas Umum'), ('Ruang Istirahat Dokter', 'Ruang Istirahat Dokter'), ('Lainnya', 'Lainnya')], max_length=100, verbose_name='Ruangan'),
        ),
    ]
