# Generated by Django 5.2.4 on 2025-09-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok_linen', '0002_alter_stoklinen_nama_linen_alter_stoklinen_ruangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoklinen',
            name='nama_linen',
            field=models.CharField(choices=[('Baju Perawat', 'Baju Perawat'), ('Baju Dokter', 'Baju Dokter'), ('Baju Pasien', 'Baju Pasien'), ('Baju Cleaner', 'Baju Cleaner'), ('Doek Besar', 'Doek Besar'), ('Doek Kecil', 'Doek Kecil'), ('Handuk Kecil', 'Handuk Kecil'), ('Laken', 'Laken'), ('Sarung Bantal', 'Sarung Bantal'), ('Selimut', 'Selimut'), ('Handuk', 'Handuk'), ('Keset', 'Keset'), ('Gown Scrub', 'Gown Scrub'), ('Mukena', 'Mukena'), ('Sejadah', 'Sejadah'), ('Bedset', 'Bedset'), ('Gorden', 'Gorden'), ('Sneli Dokter', 'Sneli Dokter')], max_length=100, verbose_name='Nama Linen'),
        ),
    ]
