# Generated by Django 5.2.4 on 2025-07-18 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, verbose_name='Judul Tugas')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('status', models.CharField(choices=[('Belum Dikerjakan', 'Belum Dikerjakan'), ('Sedang Dikerjakan', 'Sedang Dikerjakan'), ('Selesai', 'Selesai')], default='Belum Dikerjakan', max_length=20, verbose_name='Status')),
                ('tanggal_target', models.DateField(verbose_name='Tanggal Target Selesai')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('penanggung_jawab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tugas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tugas',
                'verbose_name_plural': 'Daftar Tugas',
                'ordering': ['tanggal_target'],
            },
        ),
    ]
