# Generated by Django 5.2.4 on 2025-07-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tugas',
            options={'ordering': ['target_waktu'], 'verbose_name': 'Tugas', 'verbose_name_plural': 'Daftar Tugas'},
        ),
        migrations.RemoveField(
            model_name='tugas',
            name='tanggal_target',
        ),
        migrations.AddField(
            model_name='tugas',
            name='target_waktu',
            field=models.CharField(choices=[('Minggu ke-1', 'Minggu ke-1'), ('Minggu ke-2', 'Minggu ke-2'), ('Minggu ke-3', 'Minggu ke-3'), ('Minggu ke-4', 'Minggu ke-4')], default='Minggu ke-1', max_length=20, verbose_name='Target Waktu'),
        ),
    ]
