# Generated by Django 5.2.4 on 2025-07-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_tugas_options_remove_tugas_tanggal_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugas',
            name='periode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bulan & Tahun'),
        ),
    ]
