# Generated by Django 5.2.4 on 2025-12-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_tugas_periode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tugas',
            name='judul',
            field=models.CharField(max_length=200, verbose_name='Pekerjaan'),
        ),
        migrations.AlterField(
            model_name='tugas',
            name='periode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='waktu'),
        ),
    ]
