# Generated by Django 5.2.4 on 2025-07-18 03:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=200, verbose_name='Nama Barang')),
                ('jumlah', models.PositiveIntegerField(default=1, verbose_name='Jumlah')),
                ('satuan', models.CharField(choices=[('Unit', 'Unit'), ('Pcs', 'Pcs'), ('Set', 'Set'), ('Buah', 'Buah')], default='Unit', max_length=10)),
                ('merk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Merk/Tipe')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial Number (SN)')),
                ('tahun_pengadaan', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tahun Pengadaan')),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('tanggal_input', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Input')),
            ],
            options={
                'verbose_name': 'Aset',
                'verbose_name_plural': 'Daftar Aset',
                'ordering': ['nama_barang'],
            },
        ),
    ]
