# Generated by Django 5.2.4 on 2025-07-18 03:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aset_laundry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaksiAset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_transaksi', models.CharField(choices=[('PENAMBAHAN', 'Penambahan'), ('PENGURANGAN', 'Pengurangan')], max_length=20, verbose_name='Jenis Transaksi')),
                ('jumlah', models.PositiveIntegerField()),
                ('tanggal', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Transaksi')),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('aset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaksi', to='aset_laundry.aset', verbose_name='Aset')),
                ('petugas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaksi Aset',
                'verbose_name_plural': 'Riwayat Transaksi Aset',
                'ordering': ['-tanggal'],
            },
        ),
    ]
