# Generated by Django 5.2.4 on 2025-07-17 07:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StokChemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_chemical', models.CharField(max_length=100, unique=True, verbose_name='Nama Chemical')),
                ('jumlah_stok', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Jumlah Stok')),
                ('unit', models.CharField(choices=[('Liter', 'Liter'), ('Kg', 'Kilogram'), ('Pcs', 'Pcs')], max_length=10, verbose_name='Satuan')),
                ('update_terakhir', models.DateTimeField(auto_now=True, verbose_name='Update Terakhir')),
            ],
            options={
                'verbose_name': 'Stok Chemical',
                'verbose_name_plural': 'Daftar Stok Chemical',
                'ordering': ['nama_chemical'],
            },
        ),
        migrations.CreateModel(
            name='PemakaianChemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jumlah Pemakaian')),
                ('tanggal', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal Pemakaian')),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('petugas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Petugas')),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pemakaian', to='chemical.stokchemical', verbose_name='Chemical yang Digunakan')),
            ],
            options={
                'verbose_name': 'Pemakaian Chemical',
                'verbose_name_plural': 'Riwayat Pemakaian Chemical',
                'ordering': ['-tanggal'],
            },
        ),
    ]
