# Generated by Django 5.2.4 on 2025-07-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stokchemical',
            name='nama_chemical',
            field=models.CharField(choices=[('Alkali', 'Alkali'), ('Emulsifier', 'Emulsifier'), ('Oxygen', 'Oxygen'), ('Softener', 'Softener'), ('Pelicin', 'Pelicin'), ('Chemical Lainnya', 'Chemical Lainnya')], max_length=100, unique=True, verbose_name='Nama Chemical'),
        ),
    ]
