# Generated by Django 5.2.4 on 2025-07-17 08:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical', '0002_alter_stokchemical_nama_chemical'),
    ]

    operations = [
        migrations.AddField(
            model_name='stokchemical',
            name='dibuat_pada',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Tanggal Input'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pemakaianchemical',
            name='tanggal',
            field=models.DateField(verbose_name='Tanggal Pemakaian'),
        ),
    ]
