# Generated by Django 5.2.4 on 2025-08-16 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical', '0003_stokchemical_dibuat_pada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PenerimaanChemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jumlah Masuk')),
                ('tanggal', models.DateField(verbose_name='Tanggal Penerimaan')),
                ('keterangan', models.TextField(blank=True, null=True, verbose_name='Keterangan (Contoh: No. Faktur)')),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penerimaan', to='chemical.stokchemical', verbose_name='Chemical yang Diterima')),
                ('petugas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Petugas')),
            ],
            options={
                'verbose_name': 'Penerimaan Chemical',
                'verbose_name_plural': 'Riwayat Penerimaan Chemical',
                'ordering': ['-tanggal'],
            },
        ),
    ]
